M48
; DRILL file {KiCad 9.0.2} date 2026-07-04T16:22:38+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-04T16:22:38+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.100
%
G90
G05
T1
X107.5Y-112.0
X107.5Y-142.0
X174.5Y-111.5
X174.5Y-141.5
M30
